# Generated by Django 6.0.2 on 2026-02-11 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 11, 17, 57, 14, 864644, tzinfo=datetime.timezone.utc)),
        ),
    ]
