# Generated by Django 6.0.2 on 2026-02-11 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0007_alter_expense_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='date',
            field=models.DateField(default=datetime.datetime(2026, 2, 11, 19, 13, 45, 258621, tzinfo=datetime.timezone.utc)),
        ),
    ]
