# Generated by Django 6.0.2 on 2026-02-11 17:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transfer',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2026, 2, 11, 17, 54, 19, 74794, tzinfo=datetime.timezone.utc)),
        ),
    ]
