# Generated by Django 6.0.2 on 2026-02-11 17:55

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0003_alter_transfer_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
