# Generated by Django 6.0.2 on 2026-02-11 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wallets', '0004_alter_transfer_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transfer',
            options={'ordering': ['date', '-created_at']},
        ),
    ]
